version: '2'

services:
  host-file-by-hash:
    container_name: host-file-by-hash
    depends_on:
      - redis-host-file-by-hash
    build: ./
    image: host-file-by-hash
    ports:
      - 7222:7222
    environment:
      - REDIS_URL=redis://:redis1234@redis-host-file-by-hash:6379/0 #overwrite config
    volumes:
      - ./data:/data:ro
      - ./test:/test:ro
      - ./docker/thumbnails:/host-files-by-hash/thumbnails  # for persistent thumbnails
      - ./docker/config:/host-files-by-hash/instance
    command: gunicorn --workers 4 --bind 0.0.0.0:7222 --timeout 120 'app:create_app()'
  redis-host-file-by-hash:
    container_name: redis-host-file-by-hash
    image: redis:alpine
    hostname: redis-host-file-by-hash
    volumes:
      - ./docker/redis/:/data # for a persistent database
    restart: unless-stopped
    command: redis-server --requirepass redis1234
  tor:
    container_name: tor-host-file-by-hash
    image: goldy/tor-hidden-service:0.3.5.8
    links:
      - host-file-by-hash
    environment:
        SERVICE1_TOR_SERVICE_HOSTS: 80:host-file-by-hash:7222
        SERVICE1_TOR_SERVICE_VERSION: '3'